# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c047380842d84747909db81775e80566517fa598ab094655027dfc57a8e9e7406077f2d0d3a508285504d27866fdaea3526132cd98843413aab10421cae8de25

test:
  secret_key_base: dbd76ab349144678c7031f0260d4fad92bc79e8366205d5a664cfca11dbcedeac3e6ccb1c8f696de4c2a3dc9edcf480f6990ae7a9dcf89cb1136cac7426c2830

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
